### PR TITLE
prettify demo

### PR DESCRIPTION
**Pull request by notwaldorf**
I cleaned up a looooooot of the examples in the original demo. Now there's only these ones left:

screen shot 2016-01-14 at 3 28 49 pm
screen shot 2016-01-14 at 3 24 59 pm
screen shot 2016-01-14 at 3 25 05 pm
screen shot 2016-01-14 at 3 25 12 pm

/cc @bicknellr who's going to be the future owner of this :)

### CODE REVIEW

**Comment by addyosmani** [comment]
This looks great.



Thoughts on forcing the closing tags to new lines to avoid the vertical scrollbar? i.e

```html
<paper-icon-item>
  <div class="avatar blue" item-icon></div>
  Alphonso Engelking
</paper-icon-item>
```

**Comment by notwaldorf** [comment]
Sure, I'll change that.

**Comment by notwaldorf** [comment]
Update: done

**Comment by cdata** [comment]
LGTM :+1:

**Pull request merged**
