### PR TITLE
Include tag name in paper-item-shared-styles :host selectors

### PR DESCRIPTION
**Pull request by mgiuffrida**
Fixes issue #85 (except in shady DOM due to Polymer/polymer#3610).

### CODE REVIEW

**Comment by notwaldorf** [comment]
I'm worrrrrrrried about specificity issues with this PR. :(

**Comment by mgiuffrida** [comment]
@notwaldorf yeah that's the problem I had too.

**Comment by notwaldorf** [comment]
Ok new plan. We will wait on @sorvell to fix this in Polymer, because @cdata thinks this is a fine solution and does not want the alternative (which is https://github.com/PolymerElements/paper-item/pull/89)

**Comment by mgiuffrida** [comment]
@notwaldorf what do you mean "fix this in Polymer"? What needs fixing and what will the fix look like?

**Comment by notwaldorf** [comment]
I meant the bug that you filed and linked to, and that this PR depends on before being merged

**Comment by notwaldorf** [comment]
@mgiuffrida I think the dependency Polymer PR has been merged -- would you mind double checking this PR works for you now?

Maybe if you're feeling generous, adding some tests that the right styles get applied both to a standalone `button class="paper-item"` and to one contained in a dom-module?

**Comment by mgiuffrida** [comment]
@notwaldorf Having trouble with the test. Does <style include=""> not work within a test fixture? Do I have to create my own custom element just for the test?

```
Error: fixture(...).querySelector is not a function
  Context.<anonymous> at paper-item.html:199
```

**Comment by notwaldorf** [comment]
@mgiuffrida Hmm, yeah, i think you might have to create a custom element for the test

**Comment by notwaldorf** [comment]
We've added these styles to `paper-styles/element-styles/paper-item-styles.html`, so I think we can close this PR and not bother fixing it

**Pull request closed without merging**
