### PR TITLE
Fix off-center contents in IE

### PR DESCRIPTION
**Pull request by vsimonian**
Another day, another style bug in IE.

**Chrome, working OK** | **IE being a silly willy** | **After patch**
------------------ | ---------------- | ------------------
chrome-paper-item | ie-paper-item-broken | ie-paper-item-fixed

### CODE REVIEW

**Comment by WrinklyNinja** [comment]
+1

**Comment by morethanreal** [comment]
Sigh... I think we're going to need a different implementation for this. Setting `height` instead of `min-height` on the `<paper-item>` will break the multi-line items, because the height for those items are set by the content.

**Comment by vsimonian** [comment]
@morethanreal Ah! That's a good catch. (Also, I just noticed this PR has conflicts now, so there's that, too)

It's such a pain getting IE to listen. :disappointed: There was https://github.com/PolymerElements/iron-flex-layout/pull/9 too (which also seems to have conflicts now).

**Comment by notwaldorf** [comment]
Closing this PR as it's super old and @morethanreal's comment leads me to believe it wasn't ready to be merged anyway.

**Pull request closed without merging**
