### PR TITLE
update to polymer 0.9.0-rc.1

### PR DESCRIPTION
**Pull request by morethanreal**
@cdata @notwaldorf PTAL

### CODE REVIEW

**Comment by notwaldorf** [comment]
I can't figure out how to leave comments on mobile, but I think there's two 0.8 elements still in bower.json

**Comment by morethanreal** [comment]
yeah, waiting for those to get releases before updating them in bower.json.

**Comment by notwaldorf** [comment]
We've just been updating them and holding off the parent element tag until the children are ready, I think. @cdata for double check?

**Comment by cdata** [comment]
Yah, it is very annoying to go back and make more commits for dependencies,
so have been revving everything at once. It will most likely be broken
anyway with two versions of Polymer in the dependency graph :/

**Comment by morethanreal** [comment]
Updated element versions. Looks ok?

**Comment by notwaldorf** [comment]
lgtm

**Pull request merged**
